steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/multicluster-366608/hello', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/multicluster-366608/hello']
# Deploy container image to Cloud Run for Anthos
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'hello', '--image', 'gcr.io/multicluster-366608/hello', '--cluster', 'gke-cluster', '--cluster-location', 'europe-west3-c', '--platform', 'gke']
images:
- gcr.io/multicluster-366608/hello
